target: thirdparty.VQVAEGAN.autoencoder.AutoencoderKL
#ckpt: TODO: insert ckpt here if you wanna test one of the trained models. Otherwise just ignore this line to train from scratch
params:
  ch : 32
  embed_dim : 1
  z_channels: 1
  noisy_teach_prob: 0.3
  ch_mult : [1, 2, 4, 8]
  htr_weight : 0.3
  writer_weight : 0.005
  disc_weight : 0.0

  htr_config:
    target: src.model.modules.HTR_Writer.HTR_Writer
    ckpt: #TODO this really needs a checkpoint otherwise you are training with a randomly initialized htr
    params:
      d_model: 128
      z_channels: 128
      noisy_teacher_prob: 0.3
      ch: 16
      ch_mult: [ 1, 2, 4, 8 ]
      attention_resolution: [ ]
      smooth_ce_mode: 0
      patience: 50
      num_dec_layers: 4
      num_enc_layers: 2
      double_z: False

  writer_config:
    target: src.model.modules.WriterSequence.WriterSequence
    ckpt: #TODO this really needs a checkpoint otherwise you are training with a randomly initialized writer
    params:
      num_writers: 1045
      in_channels: 1
      channels: 16
      ch_mult: [ 1,2,4,8,8 ]
      hidden_size: 256
      only_embed: False